spring:
  application:
    name: reagent-manager
  profiles:
    active: dev #默认为开发环境
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M
  jackson:
    time-zone: GMT+8

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:jp/**/mapper/*.xml
    - classpath:mapper/*.xml

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

wx:
  mp:
    appid: wxea32ea0f8041c925
    appSecret: d8625695f75773edf05a5db26a8c1692
    token: 321

base-info:
  hospital-name: 河东妇幼保健院

#redis:
#  database: mall
#  key:
#    admin: 'ums:admin'
#    resourceList: 'ums:resourceList'
#  expire:
#    common: 86400 # 24小时

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout
      - /minio/upload
      - /order/**
      - /menu/**
      - /role/**
      - /admin/**
      - /resource/**
      - /resourceCategory/**
      - /web/**
      - /baseInfo/**
      - /preInBill/upload
      - /qualification/upload
      - /wx/**

